### ISSUE TITLE
Отображение людей в локациях #2

### ISSUE THREAD

**Issue by LotusZZ** [peppersprayEzekiel/pepperspray#11]
В игре видно 62 человек
![Screenshot_247](https://user-images.githubusercontent.com/53941009/63216843-0fe34400-c144-11e9-97f9-97c0f197b9be.png)
В консоле 72
![Screenshot_248](https://user-images.githubusercontent.com/53941009/63216850-25586e00-c144-11e9-877e-17a257d70abb.png)

**Comment by peppersprayEzekiel** [comment]
У тебя уже есть один issue, добавляй информацию туда.
