### ISSUE TITLE
Provide building & running instructions

### ISSUE THREAD

**Issue by Asterix9** [peppersprayEzekiel/pepperspray#4]
Hi. I made a server a long time ago. 
I hooked in game.
I would like to try dig around. Perhaps something with profiles will come out.

But I have errors in the program, I can’t even start. It feels like something is missing.

![Screenshot_179](https://user-images.githubusercontent.com/53860009/62639994-47364180-b949-11e9-9640-8c1d12d4bcef.png)

**Comment by peppersprayEzekiel** [comment]
I'll scramble a dedicated compilation page sometimes later, ok? For now you can grab the specified dlls from the game folder.
