### ISSUE TITLE
Online database

### ISSUE THREAD

**Issue by slfl** [peppersprayEzekiel/pepperspray#5]
А в чем проблема использовать онлайн базу данных и хранить инфу на сервере, а не локально в файле рядом с игрой?
По сути дела можно ведь поднять сервер и чтоб игра читала данные с его по сокету.
Могу в этом плане помочь. Так не особо и нужно будет патчить клиент игры, а просто перенаправить поток на свой сервер.

**Comment by peppersprayEzekiel** [comment]
Так игра так и работает. Только логин использует socket.io, к которому больше нету нормальной имплементации на c#, по этому работает локально. А реализовывать полноценную инфраструктуру с несколькими серверами и шаренной базой данных мне пока лень.

**Comment by slfl** [comment]
Раньше игра отлично работала тупо через веб ядро, а socket.io был чисто для связки нескольких людей в одной локации и обработка мувмент системы, публичные дома и так далее.
А теперь, когда node.js стал поддерживать более-менее лучше многопоточность, разрабы перешли на его, и заполировали это всё 443 портом...

**Comment by slfl** [comment]
Да и нету ничего сверхестественного подключать игру по сокету на шарпе)

**Comment by peppersprayEzekiel** [comment]
В игре сейчас 4 сервера:

* обычные сокеты (чат, анимации)
* http сервер #1 (локации)
* http сервер #2 (персонажи, профили)
* socket.io сервер (логин, нотификации про server maintance)

pepperspray на данном этапе частично или полностью реализует первые три, так как рабочей библиотеки для socket.io сервера на c# я не нашел.

**Comment by slfl** [comment]
Ошибся, сорян. Да, игра использует ssl. И сокет висит на 3002 порте.
А первые 3 сервера банально можно написать на php. Раньше, при 300 клиенте я так и делал, и все отлично работало)
Только ядро работало по другому.
А сейчас просто можно использовать websocket и на шарпе он тоже есть)

**Comment by peppersprayEzekiel** [comment]
Видимо socket.io как раз через ssl и работает, понятно.

Не знаю почему ты продолжаешь говорить о веб-сокетах, потому что логин сервер работает именно на socket.io, что является отличным от websocket протоколом (ну или, возможно, наработкой над ним, на счет этого не уверен). Я проверял.

Если что первые три сервера уже написаны. У меня в планах сделать четвертый простенький socket.io сервер, который просто будет перенаправлять запросы на полноценный сервер pepperspay (все еще хочется держать основной сервер максимально централизированным, что бы не нужно было возиться с распределенными БД и всем прочим).

**Comment by slfl** [comment]
[Вот пример](https://streamable.com/tbaio)  как может работать сокет на шарпе.
Делалось не так давно.

**Comment by slfl** [comment]
Да и я ошибся, я знаю что сейчас логин сервер висит на socket.io, раньше делалось куда проще.
И иметь БД возможно будет очень даже не плохо,

**Comment by peppersprayEzekiel** [comment]
Implemented \ Сделано.
